"use client"
const quotes = [
  "Discipline is choosing between what you want now and what you want most.",
  "Success doesn’t come from motivation, it comes from discipline.",
  "Small disciplines repeated daily lead to great achievements.",
  "Discipline is the bridge between goals and accomplishment.",
  "You will never always be motivated, so you must learn to be disciplined.",
  "Discipline is doing what needs to be done, even when you don’t feel like doing it.",
  "The pain of discipline is far less than the pain of regret.",
  "Without discipline, there is no progress.",
  "Discipline turns dreams into plans and plans into reality.",
  "If you want results, you must embrace discipline.",
  "Discipline is the foundation of self-respect.",
  "Consistency is the true test of discipline.",
  "Discipline creates freedom.",
  "Master yourself and you will master your life.",
  "Discipline is the silent force behind every success story.",
  "Hard work beats talent when talent lacks discipline.",
  "Your future is shaped by your daily discipline.",
  "Discipline is staying committed long after the mood has left.",
  "Self-control is strength. Discipline is power.",
  "Greatness is built on disciplined habits.",
  "Discipline means showing up, especially on the hard days.",
  "Control your habits or they will control you.",
  "Discipline is the art of training your mind to obey your goals.",
  "Where discipline leads, success follows.",
  "Discipline is sacrifice today for a better tomorrow.",
  "The disciplined mind builds a disciplined life.",
  "Excuses fade where discipline exists.",
  "Discipline is choosing long-term growth over short-term comfort.",
  "Your level of discipline determines your level of success.",
  "True confidence comes from disciplined preparation.",
  "Discipline is the key that unlocks potential.",
  "Stay disciplined and let your results speak.",
  "Discipline is not punishment; it is empowerment.",
  "Winning starts with disciplined thinking.",
  "Be stronger than your strongest excuse.",
  "Discipline builds character and character builds destiny.",
  "Every disciplined action compounds over time.",
  "Focus, effort, discipline — repeat.",
  "Discipline is consistency under pressure.",
  "Freedom in life requires discipline in habits.",
  "The secret to success is daily disciplined effort.",
  "Discipline is the difference between interest and commitment.",
  "Train your mind to stay disciplined when it matters most.",
  "Discipline today creates opportunity tomorrow.",
  "Your habits reflect your discipline.",
  "Discipline fuels productivity.",
  "Stay disciplined, stay dangerous.",
  "What you practice daily becomes your reality.",
  "Discipline is the quiet commitment to excellence.",
  "Results respect discipline.",
];
export default function getRandomQuote() {
  const randIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randIndex];
}
